jobs:
  deploy:
    executor:
      name: node/default
      tag: "10.4"
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run:
          name: Run coverage
          command: npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
orbs:
  node: circleci/node@1.1
version: 2.1
# f9aae1627b855fa670f94b2923e39c4b06e9d92b
