jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Run coverage
          command: npm run coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
orbs:
  node: circleci/node@4.0.0
version: 2.1
