remote_theme: tomjoht/documentation-theme-jekyll
color_scheme: "light"
logo: "/logo.png"
heading_anchors: true
footer_content: ""
aux_links:
  "view on GitHub":
    - "//github.com/jonbnewman/mobx-store-provider"
ga_tracking: UA-158980290-1
