remote_theme: pmarsceill/just-the-docs
color_scheme: "light"
logo: "/logo-light.png"
heading_anchors: true
footer_content: ""
aux_links:
  "view on GitHub":
    - "//github.com/jonbnewman/mobx-store-provider"
ga_tracking: UA-158980290-1
